Creating an array

In [ ]:
!pip install numpy
import numpy as np

In [ ]:
#1D Array
n1=np.array([1,2,3])
print('n1=',n1)

#2D Array
n2=np.array([[1,2,3],[4,5,6]])
print('n2=',n2)

#Zero filled array
n3=np.zeros([])
print('n3=',n3)

#zero filled array for 3 rows & 5 columns
n4=np.zeros([3,5],dtype=int)
print('n4=',n4)

#ones filled array
n5=np.ones([2,3],dtype=int)
print('n5=',n5)

#Empty array random / junk values
n6=np.empty([2,4])
print('n6=',n6)

#create an with a range of values
n7=np.arange(5)
print('n7=',n7)

#linespace
n8=np.linspace(1,20,num=5, dtype=int)
print('n8=',n8)

#full
n9=np.full([2,5],67)
print('n9=',n9)

#fill
n5.fill(9)
print('n5=',n5)

n1= [1 2 3]
n2= [[1 2 3]
 [4 5 6]]
n3= 0.0
n4= [[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
n5= [[1 1 1]
 [1 1 1]]
n6= [[5.06661172e-310 0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000]]
n7= [0 1 2 3 4]
n8= [ 1  5 10 15 20]
n9= [[67 67 67 67 67]
 [67 67 67 67 67]]
n5= [[9 9 9]
 [9 9 9]]


In [ ]:
#Accesssing Array
print(n1)
print(n1[0]) # print 1st element
print(n1[-1]) # print last element
print(n2)
print(n2[1,0]) #n2[0]-1st list n2[1]-2nd list
print(n2[1,:]) # print evrything in the 1st list
print(n2[:,1]) # print evrything in the 2nd column
n4=np.ones([2,3,4],dtype=int)
print(n4)
n4[1,1,2]=10
print(n4)

[1 2 3]
1
3
[[1 2 3]
 [4 5 6]]
4
[4 5 6]
[2 5]
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]
[[[ 1  1  1  1]
  [ 1  1  1  1]
  [ 1  1  1  1]]

 [[ 1  1  1  1]
  [ 1  1 10  1]
  [ 1  1  1  1]]]


In [ ]:
#Size & Shape
print(n4.ndim) # dimension
print(n4.size) # size or no of elements
print(n4.shape) # arryas,row,columns we have
print(n4.dtype) # data type
print(n4.itemsize) # byte size of one element
print(n4.nbytes) # total byte size


3
24
(2, 3, 4)
int64
8
192


In [ ]:
#sorting
n10=np.array([7,2,9,10,1,6,3,4,15])
np.sort(n10)

n11=np.array([[[7,2,3],[3,15,0]],[[2,99,25],[100,0,19]]])
np.sort(n11,axis=0)



array([[[  2,   2,   3],
        [  3,   0,   0]],

       [[  7,  99,  25],
        [100,  15,  19]]])

In [ ]:
# Reshaping
print(n10)
n12=n10.reshape(3,3)
print(n12)

[ 7  2  9 10  1  6  3  4 15]
[[ 7  2  9]
 [10  1  6]
 [ 3  4 15]]


In [ ]:
#Joining Array
n13=np.arange(4)
n14=np.arange(5,9)
n15=np.concatenate([n13,n14])
print(n13)
print(n14)
print(n15)

[0 1 2 3]
[5 6 7 8]
[0 1 2 3 5 6 7 8]


In [ ]:
#Converting 1D to 2D
n16=np.arange(8)
print(n16)
n17=n16[np.newaxis,:]
print(n17)
print(n17.shape)
n18=n16[:,np.newaxis]
print(n18)
print(n18.shape)
n19=np.expand_dims(n16,axis=0)
print(n19)
n20=np.expand_dims(n16,axis=1)
print(n20)

[0 1 2 3 4 5 6 7]
[[0 1 2 3 4 5 6 7]]
(1, 8)
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]]
(8, 1)
[[0 1 2 3 4 5 6 7]]
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]]


In [ ]:
#Indexing & Slicing
n21=np.arange(10)
print(n21)
print(n21[(n21>3) & (n21<8)])
grater_than_five=n21>5
print(grater_than_five)
print(n21[grater_than_five])
print(n21[3:7])
n21[6]=100
print(n21[3:7])



[0 1 2 3 4 5 6 7 8 9]
[4 5 6 7]
[False False False False False False  True  True  True  True]
[6 7 8 9]
[3 4 5 6]
[  3   4   5 100]


In [ ]:
#stack & split
n22=np.array([[1,2],[3,4]])
n23=np.array([[5,6],[7,8]])
np.hstack((n22,n23))
np.vstack((n22,n23))
n24=np.arange(20).reshape(4,5)
print(n24)
np.hsplit(n24,5)
np.vsplit(n24,4)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


[array([[0, 1, 2, 3, 4]]),
 array([[5, 6, 7, 8, 9]]),
 array([[10, 11, 12, 13, 14]]),
 array([[15, 16, 17, 18, 19]])]

In [ ]:
n24=np.arange(20).reshape(4,5)
print(n24)
np.hsplit(n24,5)
np.vsplit(n24,4)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [ ]:
#copy
n25=n24
print(n24)
print(n25)
n24[0]=100
print(n24)
print(n25)

[[100 100 100 100 100]
 [  5   6   7   8   9]
 [ 10  11  12  13  14]
 [ 15  16  17  18  19]]
[[100 100 100 100 100]
 [  5   6   7   8   9]
 [ 10  11  12  13  14]
 [ 15  16  17  18  19]]
[[100 100 100 100 100]
 [  5   6   7   8   9]
 [ 10  11  12  13  14]
 [ 15  16  17  18  19]]
[[100 100 100 100 100]
 [  5   6   7   8   9]
 [ 10  11  12  13  14]
 [ 15  16  17  18  19]]


In [ ]:
#shallow copy
n25=n24[0:5]
n24[0]=100
print(n24)
print(n25)

[[100 100 100 100 100]
 [  5   6   7   8   9]
 [ 10  11  12  13  14]
 [ 15  16  17  18  19]]
[[100 100 100 100 100]
 [  5   6   7   8   9]
 [ 10  11  12  13  14]
 [ 15  16  17  18  19]]


In [ ]:
#deep copy
import copy
n26=copy.deepcopy(n24)


print(n26)
print(n24)



[[100 100 100 100 100]
 [200 200 200 200 200]
 [ 10  11  12  13  14]
 [ 15  16  17  18  19]]
[[100 100 100 100 100]
 [200 200 200 200 200]
 [ 10  11  12  13  14]
 [ 15  16  17  18  19]]


In [ ]:
#Math Functions
print(n26.sum())
print(n26.max())
print(n26.min())
print(n26*10)
np.cos(n26)

1645
200
10
[[1000 1000 1000 1000 1000]
 [2000 2000 2000 2000 2000]
 [ 100  110  120  130  140]
 [ 150  160  170  180  190]]


array([[ 0.86231887,  0.86231887,  0.86231887,  0.86231887,  0.86231887],
       [ 0.48718768,  0.48718768,  0.48718768,  0.48718768,  0.48718768],
       [-0.83907153,  0.0044257 ,  0.84385396,  0.90744678,  0.13673722],
       [-0.75968791, -0.95765948, -0.27516334,  0.66031671,  0.98870462]])

In [ ]:
#Random Functions
np.random.rand(3,3)
n27=np.random.randint(100,size=(4,2))
n27


array([[82, 68],
       [29, 94],
       [31, 17],
       [ 8, 82]])

In [ ]:
print(np.sqrt(n27))
print(np.exp(n27))

[[9.05538514 8.24621125]
 [5.38516481 9.69535971]
 [5.56776436 4.12310563]
 [2.82842712 9.05538514]]
[[4.09399696e+35 3.40427605e+29]
 [3.93133430e+12 6.66317622e+40]
 [2.90488497e+13 2.41549528e+07]
 [2.98095799e+03 4.09399696e+35]]


In [ ]:
#multiplication
m1=np.array([[1,2],[3,4]])
m2=np.array([[5,2],[3,6]])
print(m1)
print(m2)

m3=np.dot(m1,m2)
print(m3)


#inverse matrix
n4=np.linalg.inv(m1)
print(n4)


[[1 2]
 [3 4]]
[[5 2]
 [3 6]]
[[11 14]
 [27 30]]
[[-2.   1. ]
 [ 1.5 -0.5]]
